# Site settings
title: Patrick Does Coding 
header-img: img/home-bg.png
email: lumenfuzz@gmail.com
copyright_name: lumenfuzz
description: > # this means to ignore newlines until "baseurl:"
  this is Patrick
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lumenfuzz
learn_profile: lumenfuzz
email_username: lumenfuzz@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
